# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Create and publish a Docker image

on:
  push:
    branches: ['master']

jobs:
  create-envfile:
 
    runs-on: ubuntu-latest
 
    steps:
<<<<<<< HEAD
    - name: Create .env file
      run: |
        echo SERVICE_NAME="note-app" > .env
        echo DB_NAME=${{ secrets.DB_NAME}} >> .env
        echo DB_PASS=${{ secrets.DB_PASS}} >> .env
        echo DB_USER=${{ secrets.DB_USER}} >> .env
        echo DB_HOST=${{ secrets.DB_HOST}} >> .env
    
    - name: Check the file
      run: ls -la
=======
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_SERVICE_NAME: "note-app"
        envkey_DB_HOST: ${{ secrets.DB_HOST }}
        envkey_DB_USER: ${{ secrets.DB_USER }}
        envkey_DB_PASS: ${{ secrets.DB_PASS }}
        envkey_DB_NAME: ${{ secrets.DB_NAME }}
>>>>>>> 37616fafaa2d9ea163a609f53184047ef52d3a10

    - name: Check Out Repo 
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/backend-j3ndra

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
